// Demo data laid out exactly like the UI reference
export const doctors = [
  { name: "Dr. Rahul Sharma", exp: "M | 3 years of experience", id: "D0654321", contact: "+91 9876543210", email: "rajesh.kumar@example.com", location: "Akola, MH", specialization: "General Physician", specializationMore: 1, designation: "DVM in Veterinary Medicine" },
  { name: "Dr. Arjun Singh", exp: "F | 9 years of experience", id: "DO456789", contact: "+91 7654321098", email: "suresh.patel@mail.com", location: "Jaipur, RJ", specialization: "General Physician", specializationMore: 1, designation: "MSc in Artificial Intelligence" },
  { name: "Dr. Kavya Nair", exp: "M | 8 years of experience", id: "D0789123", contact: "+91 5432109876", email: "vikram.agarwal@service.com", location: "Chennai, TN", specialization: "General Physician", specializationMore: 1, designation: "MSc in Data Science" },
  { name: "Dr. Rahul Choudhury", exp: "F | 3 years of experience", id: "D0987654", contact: "+91 8765432109", email: "anita.sharma@domain.com", location: "Pune, MH", specialization: "General Physician", specializationMore: 1, designation: "PhD in Chemistry" },
  { name: "Dr. Sneha Joshi", exp: "M | 8 years of experience", id: "D0321987", contact: "+91 6543210987", email: "neha.singh@webmail.com", location: "Bhopal, MP", specialization: "General Physician", specializationMore: 1, designation: "MS in Civil Engineering" },
  { name: "Dr. Vikram Patel", exp: "F | 6 years of experience", id: "DO123456", contact: "+91 6543210987", email: "neha.singh@webmail.com", location: "Bhopal, MP", specialization: "General Physician", specializationMore: 1, designation: "MSc in Environmental Science" },
  { name: "Dr. Riya Verma", exp: "M | 2 years of experience", id: "DO234567", contact: "+91 9876543211", email: "deepak.rao@company.com", location: "Delhi, DL", specialization: "General Physician", specializationMore: 1, designation: "MFA in Creative Writing" },
  { name: "Dr. Karan Sharma", exp: "F | 5 years of experience", id: "DO345678", contact: "+91 8765432110", email: "pooja.patel@gmail.com", location: "Ahmedabad, GJ", specialization: "General Physician", specializationMore: 1, designation: "PhD in Neuroscience" },
  { name: "Dr. Meera Tiwari", exp: "M | 1 year of experience", id: "DO456789", contact: "+91 7654321097", email: "rahul.kumar@business.com", location: "Hyderabad, TG", specialization: "General Physician", specializationMore: 1, designation: "MSc in Biochemistry" },
  { name: "Dr. Deepak Prasad", exp: "F | 6 years of experience", id: "DO111222", contact: "+91 1234567890", email: "sita.verma@xyz.com", location: "Mumbai, MH", specialization: "02/03/2025 | 1:00 PM", specializationMore: 1, designation: "MBA in Healthcare Management" },
  { name: "Dr. Nisha Talwar", exp: "F | 5 years of experience", id: "DO333444", contact: "+91 0987654321", email: "karan.mittal@example.com", location: "Kolkata, WB", specialization: "02/03/2025 | 1:30 PM", specializationMore: 1, designation: "MD Pediatrics" },
  { name: "Dr. Himanshu Gupta", exp: "M | 4 years of experience", id: "DO555666", contact: "+91 1122334455", email: "ravi.sharma@mail.com", location: "Lucknow, UP", specialization: "02/03/2025 | 2:00 PM", specializationMore: 1, designation: "MEng in Software Engineering" },
  { name: "Dr. Suman Rao", exp: "F | 2 years of experience", id: "DO777888", contact: "+91 9988776655", email: "priya.jain@service.com", location: "Noida, UP", specialization: "02/03/2025 | 2:30 PM", specializationMore: 1, designation: "MS Orthopedic" },
  { name: "Dr. Pooja Jain", exp: "M | 5 years of experience", id: "DO999000", contact: "+91 2233445566", email: "manoj.kumar@xyz.com", location: "Ahmedabad, GJ", specialization: "02/03/2025 | 3:00 PM", specializationMore: 1, designation: "MFA in Film Production" },
  { name: "Dr. Sameer Gupta", exp: "F | 8 years of experience", id: "DO888999", contact: "+91 3344556677", email: "sonia.patel@domain.com", location: "Surat, GJ", specialization: "02/03/2025 | 3:30 PM", specializationMore: 1, designation: "MD in Cardiology" },
];
