export const indianCities = [
    "Mumbai, Maharashtra",
    "Delhi, Delhi",
    "Bengaluru, Karnataka",
    "Hyderabad, Telangana",
    "Ahmedabad, Gujarat",
    "Chennai, Tamil Nadu",
    "Kolkata, West Bengal",
    "Surat, Gujarat",
    "Pune, Maharashtra",
    "Jaipur, Rajasthan",
    "Lucknow, Uttar Pradesh",
    "Kanpur, Uttar Pradesh",
    "Nagpur, Maharashtra",
    "Indore, Madhya Pradesh",
    "Thane, Maharashtra",
    "Bhopal, Madhya Pradesh",
    "Visakhapatnam, Andhra Pradesh",
    "Pimpri-Chinchwad, Maharashtra",
    "Patna, Bihar",
    "Vadodara, Gujarat",
    "Ghaziabad, Uttar Pradesh",
    "Ludhiana, Punjab",
    "Agra, Uttar Pradesh",
    "Nashik, Maharashtra",
    "Ranchi, Jharkhand",
    "Faridabad, Haryana",
    "Meerut, Uttar Pradesh",
    "Rajkot, Gujarat",
    "Kalyan-Dombivli, Maharashtra",
    "Vasai-Virar, Maharashtra",
    "Varanasi, Uttar Pradesh",
    "Srinagar, Jammu and Kashmir",
    "Aurangabad, Maharashtra",
    "Dhanbad, Jharkhand",
    "Amritsar, Punjab",
    "Navi Mumbai, Maharashtra",
    "Allahabad, Uttar Pradesh",
    "Howrah, West Bengal",
    "Gwalior, Madhya Pradesh",
    "Jabalpur, Madhya Pradesh",
    "Coimbatore, Tamil Nadu",
    "Vijayawada, Andhra Pradesh",
    "Jodhpur, Rajasthan",
    "Madurai, Tamil Nadu",
    "Raipur, Chhattisgarh",
    "Kota, Rajasthan",
    "Chandigarh, Chandigarh",
    "Guwahati, Assam",
    "Solapur, Maharashtra",
    "Hubli–Dharwad, Karnataka",
    "Mysore, Karnataka",
    "Tiruchirappalli, Tamil Nadu",
    "Bareilly, Uttar Pradesh",
    "Aligarh, Uttar Pradesh",
    "Tiruppur, Tamil Nadu",
    "Gurgaon, Haryana",
    "Moradabad, Uttar Pradesh",
    "Jalandhar, Punjab",
    "Bhubaneswar, Odisha",
    "Salem, Tamil Nadu",
    "Warangal, Telangana",
    "Guntur, Andhra Pradesh",
    "Bhiwandi, Maharashtra",
    "Saharanpur, Uttar Pradesh",
    "Gorakhpur, Uttar Pradesh",
    "Bikaner, Rajasthan",
    "Amravati, Maharashtra",
    "Noida, Uttar Pradesh",
    "Jamshedpur, Jharkhand",
    "Bhilai, Chhattisgarh",
    "Cuttack, Odisha",
    "Firozabad, Uttar Pradesh",
    "Kochi, Kerala",
    "Nellore, Andhra Pradesh",
    "Bhavnagar, Gujarat",
    "Dehradun, Uttarakhand",
    "Durgapur, West Bengal",
    "Asansol, West Bengal",
    "Rourkela, Odisha",
    "Nanded, Maharashtra",
    "Kolhapur, Maharashtra",
    "Ajmer, Rajasthan",
    "Gulbarga, Karnataka",
    "Jamnagar, Gujarat",
    "Ujjain, Madhya Pradesh",
    "Loni, Uttar Pradesh",
    "Siliguri, West Bengal",
    "Jhansi, Uttar Pradesh",
    "Ulhasnagar, Maharashtra",
    "Nellore, Andhra Pradesh",
    "Jammu, Jammu and Kashmir",
    "Sangli-Miraj & Kupwad, Maharashtra",
    "Belgaum, Karnataka",
    "Mangalore, Karnataka",
    "Ambattur, Tamil Nadu",
    "Tirunelveli, Tamil Nadu",
    "Malegaon, Maharashtra",
    "Gaya, Bihar",
    "Jalgaon, Maharashtra",
    "Udaipur, Rajasthan",
    "Maheshtala, West Bengal",
    "Davanagere, Karnataka",
    "Kozhikode, Kerala",
    "Akola, Maharashtra",
    "Kurnool, Andhra Pradesh",
    "Rajpur Sonarpur, West Bengal",
    "Rajahmundry, Andhra Pradesh",
    "Bokaro, Jharkhand",
    "South Dumdum, West Bengal",
    "Bellary, Karnataka",
    "Patiala, Punjab",
    "Gopalpur, West Bengal",
    "Agartala, Tripura",
    "Bhagalpur, Bihar",
    "Muzaffarnagar, Uttar Pradesh",
    "Bhatpara, West Bengal",
    "Panihati, West Bengal",
    "Latur, Maharashtra",
    "Dhule, Maharashtra",
    "Rohtak, Haryana",
    "Sagar, Madhya Pradesh",
    "Korba, Chhattisgarh",
    "Bhilwara, Rajasthan",
    "Berhampur, Odisha",
    "Muzaffarpur, Bihar",
    "Ahmednagar, Maharashtra",
    "Mathura, Uttar Pradesh",
    "Kollam, Kerala",
    "Avadi, Tamil Nadu",
    "Kadapa, Andhra Pradesh",
    "Kamarhati, West Bengal",
    "Sambalpur, Odisha",
    "Bilaspur, Chhattisgarh",
    "Shahjahanpur, Uttar Pradesh",
    "Satara, Maharashtra",
    "Bijapur, Karnataka",
    "Rampur, Uttar Pradesh",
    "Shimoga, Karnataka",
    "Chandrapur, Maharashtra",
    "Junagadh, Gujarat",
    "Thrissur, Kerala",
    "Alwar, Rajasthan",
    "Bardhaman, West Bengal",
    "Kulti, West Bengal",
    "Nizamabad, Telangana",
    "Parbhani, Maharashtra",
    "Tumkur, Karnataka",
    "Khammam, Telangana",
    "Uzhavarkarai, Puducherry",
    "Bihar Sharif, Bihar",
    "Panipat, Haryana",
    "Darbhanga, Bihar",
    "Bally, West Bengal",
    "Aizawl, Mizoram",
    "Dewas, Madhya Pradesh",
    "Ichalkaranji, Maharashtra",
    "Karnal, Haryana",
    "Bathinda, Punjab",
    "Jalna, Maharashtra",
    "Eluru, Andhra Pradesh",
    "Kirari Suleman Nagar, Delhi",
    "Barasat, West Bengal",
    "Purnia, Bihar",
    "Satna, Madhya Pradesh",
    "Mau, Uttar Pradesh",
    "Sonipat, Haryana",
    "Farrukhabad, Uttar Pradesh",
    "Sagar, Madhya Pradesh",
    "Rourkela, Odisha",
    "Durg, Chhattisgarh",
    "Imphal, Manipur",
    "Ratlam, Madhya Pradesh",
    "Hapur, Uttar Pradesh",
    "Anantapur, Andhra Pradesh",
    "Arrah, Bihar",
    "Karimnagar, Telangana",
    "Etawah, Uttar Pradesh",
    "Ambernath, Maharashtra",
    "North Dumdum, West Bengal",
    "Bharatpur, Rajasthan",
    "Begusarai, Bihar",
    "New Delhi, Delhi",
    "Gandhidham, Gujarat",
    "Baranagar, West Bengal",
    "Tiruvottiyur, Tamil Nadu",
    "Pondicherry, Puducherry",
    "Sikar, Rajasthan",
    "Thoothukudi, Tamil Nadu",
    "Rewa, Madhya Pradesh",
    "Mirzapur, Uttar Pradesh",
    "Raichur, Karnataka",
    "Pali, Rajasthan",
    "Ramagundam, Telangana",
    "Haridwar, Uttarakhand",
    "Vijayanagaram, Andhra Pradesh",
    "Katihar, Bihar",
    "Nagercoil, Tamil Nadu",
    "Sri Ganganagar, Rajasthan",
    "Karur, Tamil Nadu",
    "Mango, Jharkhand",
    "Thanjavur, Tamil Nadu",
    "Bulandshahr, Uttar Pradesh",
    "Uluberia, West Bengal",
    "Murwara, Madhya Pradesh",
    "Sambhal, Uttar Pradesh",
    "Singrauli, Madhya Pradesh",
    "Nadiad, Gujarat",
    "Secunderabad, Telangana",
    "Naihati, West Bengal",
    "Yamunanagar, Haryana",
    "Bidhan Nagar, West Bengal",
    "Pallavaram, Tamil Nadu",
    "Bidar, Karnataka",
    "Munger, Bihar",
    "Panchkula, Haryana",
    "Burhanpur, Madhya Pradesh",
    "Raurkela Industrial Township, Odisha",
    "Kharagpur, West Bengal",
    "Dindigul, Tamil Nadu",
    "Gandhinagar, Gujarat",
    "Hospet, Karnataka",
    "Nangloi Jat, Delhi",
    "Malda, West Bengal",
    "Ongole, Andhra Pradesh",
    "Deoghar, Jharkhand",
    "Chapra, Bihar",
    "Haldia, West Bengal",
    "Khandwa, Madhya Pradesh",
    "Nandyal, Andhra Pradesh",
    "Morena, Madhya Pradesh",
    "Amroha, Uttar Pradesh",
    "Anand, Gujarat",
    "Bhind, Madhya Pradesh",
    "Bhalswa Jahangir Pur, Delhi",
    "Madhyamgram, West Bengal",
    "Bhivandi, Maharashtra",
    "Berhampore, West Bengal",
    "Morvi, Gujarat",
    "Fatehpur, Uttar Pradesh",
    "Raebareli, Uttar Pradesh",
    "Khas Hindustan, West Bengal",
    "Bhiwani, Haryana",
    "Ozhukarai, Puducherry",
    "Baharampur, West Bengal",
    "Ambala, Haryana",
    "Moradabad, Uttar Pradesh"
];
