export const indianMedicalColleges = [
    { value: "All India Medical College and University", label: "All India Medical College and University" },
    { value: "All India Institute of Medical Sciences, New Delhi", label: "All India Institute of Medical Sciences, New Delhi" },
    { value: "Post Graduate Institute of Medical Education and Research, Chandigarh", label: "Post Graduate Institute of Medical Education and Research, Chandigarh" },
    { value: "Christian Medical College, Vellore", label: "Christian Medical College, Vellore" },
    { value: "National Institute of Mental Health and Neuro Sciences, Bangalore", label: "National Institute of Mental Health and Neuro Sciences, Bangalore" },
    { value: "Sanjay Gandhi Postgraduate Institute of Medical Sciences, Lucknow", label: "Sanjay Gandhi Postgraduate Institute of Medical Sciences, Lucknow" },
    { value: "Amrita Vishwa Vidyapeetham, Coimbatore", label: "Amrita Vishwa Vidyapeetham, Coimbatore" },
    { value: "Banaras Hindu University, Varanasi", label: "Banaras Hindu University, Varanasi" },
    { value: "Jawaharlal Institute of Post Graduate Medical Education & Research, Puducherry", label: "Jawaharlal Institute of Post Graduate Medical Education & Research, Puducherry" },
    { value: "King George's Medical University, Lucknow", label: "King George's Medical University, Lucknow" },
    { value: "Madras Medical College, Chennai", label: "Madras Medical College, Chennai" },
    { value: "Grant Medical College, Mumbai", label: "Grant Medical College, Mumbai" },
    { value: "Seth GS Medical College, Mumbai", label: "Seth GS Medical College, Mumbai" },
    { value: "Sri Ramachandra Institute of Higher Education and Research, Chennai", label: "Sri Ramachandra Institute of Higher Education and Research, Chennai" },
    { value: "St. John's Medical College, Bangalore", label: "St. John's Medical College, Bangalore" },
    { value: "Aligarh Muslim University, Aligarh", label: "Aligarh Muslim University, Aligarh" },
    { value: "Christian Medical College, Ludhiana", label: "Christian Medical College, Ludhiana" },
    { value: "Kasturba Medical College, Manipal", label: "Kasturba Medical College, Manipal" },
    { value: "University College of Medical Sciences, Delhi", label: "University College of Medical Sciences, Delhi" },
    { value: "JSS Medical College, Mysore", label: "JSS Medical College, Mysore" },
    { value: "Vardhman Mahavir Medical College & Safdarjung Hospital, New Delhi", label: "Vardhman Mahavir Medical College & Safdarjung Hospital, New Delhi" },
    { value: "Lady Hardinge Medical College, New Delhi", label: "Lady Hardinge Medical College, New Delhi" },
    { value: "Maulana Azad Medical College, New Delhi", label: "Maulana Azad Medical College, New Delhi" },
    { value: "Dayanand Medical College & Hospital, Ludhiana", label: "Dayanand Medical College & Hospital, Ludhiana" },
    { value: "Sawai Man Singh Medical College, Jaipur", label: "Sawai Man Singh Medical College, Jaipur" },
    { value: "Jamia Hamdard, New Delhi", label: "Jamia Hamdard, New Delhi" },
    { value: "Siksha 'O' Anusandhan, Bhubaneswar", label: "Siksha 'O' Anusandhan, Bhubaneswar" },
    { value: "Dr. D. Y. Patil Vidyapeeth, Pune", label: "Dr. D. Y. Patil Vidyapeeth, Pune" },
    { value: "SRM Institute of Science and Technology, Chennai", label: "SRM Institute of Science and Technology, Chennai" },
    { value: "Institute of Liver and Biliary Sciences, New Delhi", label: "Institute of Liver and Biliary Sciences, New Delhi" },
    { value: "Jawaharlal Nehru Medical College, Belagavi", label: "Jawaharlal Nehru Medical College, Belagavi" },
    { value: "Chettinad Hospital and Research Institute, Kelambakkam", label: "Chettinad Hospital and Research Institute, Kelambakkam" },
    { value: "Datta Meghe Institute of Higher Education and Research, Wardha", label: "Datta Meghe Institute of Higher Education and Research, Wardha" },
    { value: "Maharishi Markandeshwar, Mullana", label: "Maharishi Markandeshwar, Mullana" },
    { value: "Kalinga Institute of Industrial Technology, Bhubaneswar", label: "Kalinga Institute of Industrial Technology, Bhubaneswar" },
    { value: "Saveetha Institute of Medical and Technical Sciences, Chennai", label: "Saveetha Institute of Medical and Technical Sciences, Chennai" },
    { value: "Sriher, Chennai", label: "Sriher, Chennai" },
    { value: "M. S. Ramaiah Medical College, Bangalore", label: "M. S. Ramaiah Medical College, Bangalore" },
    { value: "Government Medical College and Hospital, Chandigarh", label: "Government Medical College and Hospital, Chandigarh" },
    { value: "Pt. B. D. Sharma Post Graduate Institute of Medical Sciences, Rohtak", label: "Pt. B. D. Sharma Post Graduate Institute of Medical Sciences, Rohtak" },
    { value: "Lokmanya Tilak Municipal Medical College, Mumbai", label: "Lokmanya Tilak Municipal Medical College, Mumbai" },
    { value: "Bangalore Medical College and Research Institute, Bangalore", label: "Bangalore Medical College and Research Institute, Bangalore" },
    { value: "Osmania Medical College, Hyderabad", label: "Osmania Medical College, Hyderabad" },
    { value: "Institute of Post Graduate Medical Education and Research, Kolkata", label: "Institute of Post Graduate Medical Education and Research, Kolkata" },
    { value: "B. J. Medical College, Ahmedabad", label: "B. J. Medical College, Ahmedabad" },
    { value: "Medical College, Kolkata", label: "Medical College, Kolkata" },
    { value: "Gandhi Medical College, Hyderabad", label: "Gandhi Medical College, Hyderabad" },
    { value: "Nizam's Institute of Medical Sciences, Hyderabad", label: "Nizam's Institute of Medical Sciences, Hyderabad" },
    { value: "Topiwala National Medical College, Mumbai", label: "Topiwala National Medical College, Mumbai" },
    { value: "Government Medical College, Thiruvananthapuram", label: "Government Medical College, Thiruvananthapuram" },
    { value: "SCB Medical College, Cuttack", label: "SCB Medical College, Cuttack" },
    { value: "Byramjee Jeejeebhoy Government Medical College, Pune", label: "Byramjee Jeejeebhoy Government Medical College, Pune" },
    { value: "Andhra Medical College, Visakhapatnam", label: "Andhra Medical College, Visakhapatnam" },
    { value: "Patna Medical College, Patna", label: "Patna Medical College, Patna" },
    { value: "Government Medical College, Nagpur", label: "Government Medical College, Nagpur" },
    { value: "Indira Gandhi Medical College, Shimla", label: "Indira Gandhi Medical College, Shimla" },
    { value: "Gauhati Medical College, Guwahati", label: "Gauhati Medical College, Guwahati" },
    { value: "Rajendra Institute of Medical Sciences, Ranchi", label: "Rajendra Institute of Medical Sciences, Ranchi" },
    { value: "Mahatma Gandhi Memorial Medical College, Indore", label: "Mahatma Gandhi Memorial Medical College, Indore" },
    { value: "Government Medical College, Surat", label: "Government Medical College, Surat" },
    { value: "Government Medical College, Kozhikode", label: "Government Medical College, Kozhikode" },
    { value: "Government Medical College, Amritsar", label: "Government Medical College, Amritsar" },
    { value: "Government Medical College, Patiala", label: "Government Medical College, Patiala" },
    { value: "Gattani Hospital, Akola", label: "Gattani Hospital, Akola" },
    { value: "Ozone Multispecialty Hospital, Akola", label: "Ozone Multispecialty Hospital, Akola" },
    // Adding specific Maharashtra colleges since user mentionned Akola/Maharashtra in previous steps options
    { value: "Government Medical College, Akola", label: "Government Medical College, Akola" },
    { value: "Dr. Panjabrao Deshmukh Memorial Medical College, Amravati", label: "Dr. Panjabrao Deshmukh Memorial Medical College, Amravati" },
    { value: "Government Medical College, Aurangabad", label: "Government Medical College, Aurangabad" },
    { value: "Government Medical College, Latur", label: "Government Medical College, Latur" },
    { value: "Government Medical College, Miraj", label: "Government Medical College, Miraj" },
    { value: "Government Medical College, Nanded", label: "Government Medical College, Nanded" },
    { value: "Government Medical College, Yavatmal", label: "Government Medical College, Yavatmal" },
    { value: "R. C. S. M. Government Medical College, Kolhapur", label: "R. C. S. M. Government Medical College, Kolhapur" },
    { value: "Swami Ramanand Teerth Rural Government Medical College, Ambajogai", label: "Swami Ramanand Teerth Rural Government Medical College, Ambajogai" },
    { value: "Other", label: "Other" }
];
